---
- name: pkgs to install 
  debug: var=pkgs_install

- name: install packages
  package:
    name: "{{ pkgs_install }}"
    state: latest

- name: pkgs to remove 
  debug: var=pkgs_remove

- name: remove packages
  package:
    name: "{{ pkgs_remove }}"
    state: absent 

