---
- name: queue autojump for removal
  set_fact:
    packages: "{{ packages | combine({'remove': packages['remove'] + [ 'autojump' ] }) }}"

- name: queue fasd for installation
  set_fact:
    packages: "{{ packages | combine({'install': packages['install'] + [ 'fasd' ] }) }}"
